export const REQUEST_DOCTORS = 'REQUEST_DOCTORS';
export const RECEIVE_DOCTORS = 'RECEIVE_DOCTORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const NEW_APPOINTMENT_SUCCESS = 'NEW_APPOINTMENT_SUCCESS';
export const NEW_APPOINTMENT_FAILURE = 'NEW_APPOINTMENT_FAILURE';
export const REQUEST_APPOINTMENTS = 'REQUEST_APPOINTMENTS';
export const RECEIVE_APPOINTMENTS = 'RECEIVE_APPOINTMENTS';
