export const REQUEST_DOCTORS = 'REQUEST_DOCTORS';
export const RECEIVE_DOCTORS = 'RECEIVE_DOCTORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
